use_frameworks!
inhibit_all_warnings!

target 'SDWebImageHEIFCoder_Example' do
  platform :ios, '9.0'
  pod 'SDWebImageHEIFCoder', :path => '../', :subspecs => [
  'libde265',
  'libx265'
  ]

  target 'SDWebImageHEIFCoder_Tests' do
    inherit! :search_paths
    pod 'Expecta'
    
  end
end

target 'SDWebImageHEIFCoder_Example macOS' do
  platform :osx, '10.11'
  pod 'SDWebImageHEIFCoder', :path => '../', :subspecs => [
  'libde265',
  'libx265'
  ]
end