use_frameworks!
inhibit_all_warnings!

target 'SDWebImageHEIFCoder_Example' do
  pod 'SDWebImageHEIFCoder', :path => '../'

  target 'SDWebImageHEIFCoder_Tests' do
    inherit! :search_paths

    
  end
end
